architect:
  - dgroup

readers:
  - "urn:github:1651114"

docker:
  image: dgroup/dindx

install:
  - "docker pull openjdk:9.0.1-11"

merge:
  script:
    - mvn -Pqulice -Ddocker_installed=yes clean package

#deploy:
#  env:
#    MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
#  script:
#    - "sudo bundle"
#    - "mvn clean deploy -Prultor --settings ../settings.xml"
#    - "mvn clean site-deploy -Psite -Prempl --settings ../settings.xml"

release:
  script: |
    mvn versions:set "-DnewVersion=$tag"
    git commit -am "$tag"
    mvn clean package -Pqulice -Ddocker_installed=yes